### ISSUE TITLE
how can i get new google chrome ver 42 2015 to work using -enable-file-cookies -allow-file-access-from-files

### ISSUE THREAD

**Issue by ira237** [01org/rib#316]
how can i get new google chrome ver 42 2015 to work using -enable-file-cookies -allow-file-access-from-files. i cant get rapid interface builder to work in google

**Comment by grgustaf** [comment]
I haven't tried it with that version - is this a new problem in Chrome 42?

You should still be able to use the online version of RIB at 01.org/rib/online, I would think? Your data is still stored locally in your browser's local storage, not shared with the server. It's not the very latest code but there have been only minor fixes since that was published.

**Comment by grgustaf** [comment]
I'm not sure if this was a specific problem with Chrome 42, but I have verified RIB works file on chromium-browser 48.0.2564.82 on Ubuntu 14.04. So I don't think this is an issue.
